project_id = "gp-fdc4b247-ed10-41cb-a5f5-cf08ee21259d"
org_id = "6a937adbe959543a010e73bb"
name = "pact"
call_direction = "inbound"
base_image = "python-sandbox:3.14"
phone_number = "+14842951236"
tier = "guava-seed"
replicas = 1
enable_healthcheck = true
